---
spring:
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver


logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG

app:
  appName: "spring-kotlin-jdbi"
---
