spring:
  profiles: local
  datasource:
    #url: jdbc:postgresql://localhost:5432/app
    url: jdbc:postgresql://${APP_DB_URL}
    username: app_rw
    password: app_rw
    driver-class-name: org.postgresql.Driver


